#!/usr/bin/env python3
"""Refresh the catalogue of Valve SteamOS recovery images.

Scrapes Valve's public image index, fetches the small manifest.json beside each
build, and merges the result into data/images.yaml without touching the
hand-written notes. Then regenerates docs/images.md.

Standard library only - CI needs no pip install.

Usage:
    tools/refresh-images.py                # refresh + regenerate docs
    tools/refresh-images.py --check        # exit 1 if anything would change
    tools/refresh-images.py --limit 5      # only look at the newest N builds
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

INDEX = "https://steamdeck-images.steamos.cloud/steamdeck/"
ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "images.yaml"
DOCS = ROOT / "docs" / "images.md"
UA = "steamos_custom_install-image-refresh/1.0 (+https://github.com/louij2/steamos_custom_install)"
TIMEOUT = 30

BUILD_RE = re.compile(r'href="((\d{8}\.\d+)/)"')
FILE_RE = re.compile(r'href="([^"?/][^"]*\.(?:img\.zst|img\.zip|manifest\.json))"')


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
        return r.read().decode("utf-8", "replace")


def head(url: str) -> int | None:
    """Content-Length for a build artefact, or None if the server won't say."""
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": UA})
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            v = r.headers.get("Content-Length")
            return int(v) if v else None
    except (urllib.error.URLError, ValueError):
        return None


def list_builds() -> list[str]:
    html = fetch(INDEX)
    builds = sorted({m.group(2) for m in BUILD_RE.finditer(html)},
                    key=lambda b: [int(x) for x in b.split(".")])
    if not builds:
        raise SystemExit("!! No build directories found - has the index format changed?")
    return builds


def describe(build: str) -> dict | None:
    """Return catalogue metadata for one build directory."""
    base = f"{INDEX}{build}/"
    try:
        html = fetch(base)
    except urllib.error.URLError as e:
        print(f";; skipping {build}: {e}", file=sys.stderr)
        return None

    files = [m.group(1) for m in FILE_RE.finditer(html)]
    image = next((f for f in files if f.endswith((".img.zst", ".img.zip"))), None)
    manifest = next((f for f in files if f.endswith(".manifest.json")), None)
    if not image:
        return None

    entry: dict = {"build": build, "url": base + image, "file": image}

    if manifest:
        try:
            m = json.loads(fetch(base + manifest))
            for k in ("version", "variant", "branch", "release", "arch"):
                if m.get(k):
                    entry[k] = m[k]
        except (urllib.error.URLError, json.JSONDecodeError):
            pass

    size = head(entry["url"])
    if size:
        entry["size_bytes"] = size
        entry["size_human"] = f"{size / 1024**3:.2f} GiB"
    return entry


# --- minimal YAML I/O -------------------------------------------------------
# The file is a fixed, flat shape that we own, so a tiny reader/writer beats a
# PyYAML dependency in CI. If the schema ever grows, swap this for PyYAML.

def load_yaml(path: Path) -> dict:
    if not path.exists():
        return {"pinned": [], "tracked": []}
    data: dict = {"pinned": [], "tracked": []}
    section, cur = None, None
    for raw in path.read_text().splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if re.match(r"^(pinned|tracked):", raw):
            section = raw.split(":")[0]
            continue
        if section is None:
            continue
        if raw.lstrip().startswith("- "):
            cur = {}
            data[section].append(cur)
            raw = "  " + raw.lstrip()[2:]
        if cur is None:
            continue
        m = re.match(r"^\s+([a-z_]+):\s*(.*)$", raw)
        if m:
            k, v = m.group(1), m.group(2).strip()
            if v.startswith('"') and v.endswith('"') and len(v) > 1:
                v = v[1:-1]
            cur[k] = int(v) if re.fullmatch(r"-?\d+", v) else v
    return data


def dump_yaml(data: dict, path: Path) -> str:
    out = [
        "# Catalogue of Valve SteamOS recovery images.",
        "#",
        "# `pinned`  - hand-curated entries. Edit these freely; the refresh tool",
        "#             never rewrites them. This is where end-user notes live.",
        "# `tracked` - regenerated by tools/refresh-images.py. Do not hand-edit;",
        "#             your changes will be overwritten on the next refresh.",
        "",
        "pinned:",
    ]
    def emit(e: dict) -> None:
        keys = [k for k in ("build", "version", "file", "url", "size_bytes",
                            "size_human", "variant", "branch", "release", "arch",
                            "label", "note") if k in e]
        first = True
        for k in keys:
            v = e[k]
            v = v if isinstance(v, int) else f'"{v}"'
            out.append(f"{'  - ' if first else '    '}{k}: {v}")
            first = False

    for e in data.get("pinned", []):
        emit(e)
    if not data.get("pinned"):
        out.append("  []")
    out += ["", "tracked:"]
    for e in data.get("tracked", []):
        emit(e)
    if not data.get("tracked"):
        out.append("  []")
    return "\n".join(out) + "\n"


def render_docs(data: dict) -> str:
    def row(e: dict) -> str:
        name = e.get("label") or e.get("version") or e.get("build", "?")
        size = e.get("size_human", "-")
        note = e.get("note", "")
        branch = e.get("branch", "-")
        return (f"| [{name}]({e['url']}) | `{e.get('build','?')}` | {e.get('version','-')} "
                f"| {branch} | {size} | {note} |")

    lines = [
        "# SteamOS recovery images",
        "",
        "<!-- GENERATED by tools/refresh-images.py from data/images.yaml. Do not edit by hand. -->",
        "",
        "Every image below is hosted by Valve on `steamdeck-images.steamos.cloud`.",
        "Download one, write it to a USB stick with [Balena Etcher](https://www.balena.io/etcher/)",
        "or [Rufus](https://rufus.ie/en/), boot it, then follow the",
        "[step-by-step guide](step-by-step-guide.md).",
        "",
        "> Images ending in `.img.zst` need `zstd` to decompress. Etcher and Rufus",
        "> handle `.zip` directly; for `.zst` on Windows, use",
        "> [7-Zip-zstd](https://github.com/mcmilk/7-Zip-zstd) first.",
        "",
        "## Recommended / known-good",
        "",
        "These are chosen by hand because someone confirmed they work on specific",
        "hardware. Start here.",
        "",
        "| Image | Build | Version | Branch | Size | Notes |",
        "|---|---|---|---|---|---|",
    ]
    lines += [row(e) for e in data.get("pinned", [])] or ["| _none yet_ | | | | | |"]
    lines += [
        "",
        "## Latest builds",
        "",
        "Newest images Valve has published, refreshed automatically. These are not",
        "vetted - if one fails, try a pinned image above and please open an issue",
        "saying which build and what hardware.",
        "",
        "**Branch matters.** `main` builds target Steam Deck hardware; `pc` builds",
        "are Valve's SteamOS-for-PC line. If you are installing on a desktop or",
        "laptop, a `pc` build is usually the better starting point.",
        "",
        "| Image | Build | Version | Branch | Size | Notes |",
        "|---|---|---|---|---|---|",
    ]
    lines += [row(e) for e in data.get("tracked", [])] or ["| _none_ | | | | | |"]
    lines += [
        "",
        "---",
        "",
        "**Adding a note:** edit the `pinned` section of",
        "[`data/images.yaml`](../data/images.yaml) and open a PR. Say which machine",
        "you tested on - that is the part other people actually need.",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--limit", type=int, default=8,
                    help="how many of the newest builds to track (default: 8)")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the catalogue or docs are out of date")
    args = ap.parse_args()

    data = load_yaml(DATA)
    builds = list_builds()
    print(f":: index lists {len(builds)} builds; tracking newest {args.limit}", file=sys.stderr)

    tracked = []
    for b in reversed(builds[-args.limit:]):
        e = describe(b)
        if e:
            tracked.append(e)
            print(f"   {b}  {e.get('version','?'):8} {e.get('size_human','?')}", file=sys.stderr)
    if not tracked:
        raise SystemExit("!! Refusing to write an empty catalogue - upstream fetch failed.")
    data["tracked"] = tracked

    new_yaml, new_docs = dump_yaml(data, DATA), render_docs(data)
    old_yaml = DATA.read_text() if DATA.exists() else ""
    old_docs = DOCS.read_text() if DOCS.exists() else ""

    if args.check:
        if new_yaml != old_yaml or new_docs != old_docs:
            print("!! catalogue is out of date - run tools/refresh-images.py", file=sys.stderr)
            return 1
        print(":: catalogue up to date", file=sys.stderr)
        return 0

    DATA.parent.mkdir(parents=True, exist_ok=True)
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    DATA.write_text(new_yaml)
    DOCS.write_text(new_docs)
    changed = (new_yaml != old_yaml) or (new_docs != old_docs)
    print(f":: {'updated' if changed else 'no change to'} {DATA.name} and {DOCS.name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
